apiVersion: v1
kind: LimitRange
metadata:
  name: imb-limit
  namespace: colocation-imb
spec:
  limits:
  - type: Container
    max:
      memory: 8Gi
      cpu: 6
    min:
      memory: 512Mi
      cpu: 500m
    default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 512Mi
      cpu: 500m
