apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiny-app-pvc
  namespace: colocation-imb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem