FROM rocker/shiny-verse:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get upgrade -y --allow-unauthenticated
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libsodium-dev python3 python3-pip python3-venv

RUN python3 -m venv app/venv
RUN source app/venv/bin/activate
RUN pip install shiny




EXPOSE 3838
